"""Report data models for Markdown, HTML, and JSON representations."""

from datetime import UTC, datetime

from pydantic import BaseModel, Field

from src.contracts.evidence import ResearchEvidence
from src.contracts.market import MarketSnapshot
from src.contracts.news import AggregateSentiment, NewsArticle
from src.contracts.signal import SignalResult
from src.contracts.technical import TechnicalSnapshot


class DailyResearchReport(BaseModel):
    """Unified evidence-linked daily research report for an instrument."""

    run_id: str
    symbol: str
    analysis_timestamp: datetime
    timezone: str = "America/New_York"
    market_state: str = "BULLISH|NEUTRAL|BEARISH"
    signal_score: float
    confidence: float
    headline: str
    executive_summary: str
    snapshot: MarketSnapshot
    technical: TechnicalSnapshot
    sentiment: AggregateSentiment
    top_news: list[NewsArticle] = Field(default_factory=list)
    signal: SignalResult
    evidence: list[ResearchEvidence] = Field(default_factory=list)
    scenario_analysis: dict[str, str] = Field(default_factory=dict)
    known_limitations: list[str] = Field(default_factory=list)
    freshness_warnings: list[str] = Field(default_factory=list)
    regulatory_notice: str = (
        "RESEARCH NOTICE: This report is an automated research demonstration generated by an "
        "agentic research system. It does not constitute financial advice, investment recommendation, "
        "or an offer to buy or sell securities. Past performance does not guarantee future results."
    )
    generated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
